In [1]:
from utilities import *
from model import *
from metrics import *
import numpy as np
from scipy import stats

# Q1.0 and Q2.0

In [2]:
# Directory
file_dir = "/Users/igoradamski/Documents/cambridge/MLMI/nlp/coursework/nlp/data-tagged"

In [3]:
# Fetching training and testing data
train = DataHandler(file_dir)
test  = DataHandler(file_dir)

x_train, y_train, x_test, y_test = DataHandler.getTrainTestSet(file_dir,0,899,900,999)

train(x_train, y_train)
test(x_test, y_test)

In [11]:
# CREATING TABLES FOR LATEX
table1 = np.zeros((4,4))
table2 = np.zeros((4,4))
table3 = np.zeros((4,4))

predictions1 = {}
predictions2 = {}
predictions3 = {}

# table1
for idx1, threshold in enumerate([0,4,8,12]):
    for idx2, kappa in enumerate([0,0.5,1.5,5]):
        print('table1, thr={}, kappa={}'.format(threshold, kappa))
        model = NBModel(threshold = [threshold], grams = 'uni', smoothing = kappa)
        model.train(train.x_data, train.y_data)
        predictions = model.predict(test.x_data)
        predictions1['thr={},kappa={}'.format(threshold, kappa)] = predictions
        table1[idx1,idx2] = Metrics.getAccuracy(predictions, test.y_data)

# table2
for idx1, threshold in enumerate([0,4,8,12]):
    for idx2, kappa in enumerate([0,0.5,1.5,5]):
        print('table1, thr={}, kappa={}'.format(threshold, kappa))
        model = NBModel(threshold = [threshold], grams = 'bi', smoothing = kappa)
        model.train(train.x_data, train.y_data)
        predictions = model.predict(test.x_data)
        predictions2['thr={},kappa={}'.format(threshold, kappa)] = predictions
        table2[idx1,idx2] = Metrics.getAccuracy(predictions, test.y_data)
        
# table3
for idx1, threshold in enumerate([[0,0],[0,4],[4,8],[6,12]]):
    for idx2, kappa in enumerate([0,0.5,1.5,5]):
        print('table1, thr={}, kappa={}'.format(threshold, kappa))
        model = NBModel(threshold = threshold, grams = ['uni', 'bi'], smoothing = kappa)
        model.train(train.x_data, train.y_data)
        predictions = model.predict(test.x_data)
        predictions3['thr={},kappa={}'.format(threshold, kappa)] = predictions
        table3[idx1,idx2] = Metrics.getAccuracy(predictions, test.y_data)


table1, thr=0, kappa=0
table1, thr=0, kappa=0.5
table1, thr=0, kappa=1.5
table1, thr=0, kappa=5
table1, thr=4, kappa=0
table1, thr=4, kappa=0.5
table1, thr=4, kappa=1.5
table1, thr=4, kappa=5
table1, thr=8, kappa=0
table1, thr=8, kappa=0.5
table1, thr=8, kappa=1.5
table1, thr=8, kappa=5
table1, thr=12, kappa=0
table1, thr=12, kappa=0.5
table1, thr=12, kappa=1.5
table1, thr=12, kappa=5
table1, thr=0, kappa=0
table1, thr=0, kappa=0.5
table1, thr=0, kappa=1.5
table1, thr=0, kappa=5
table1, thr=4, kappa=0
table1, thr=4, kappa=0.5
table1, thr=4, kappa=1.5
table1, thr=4, kappa=5
table1, thr=8, kappa=0
table1, thr=8, kappa=0.5
table1, thr=8, kappa=1.5
table1, thr=8, kappa=5
table1, thr=12, kappa=0
table1, thr=12, kappa=0.5
table1, thr=12, kappa=1.5
table1, thr=12, kappa=5
table1, thr=[0, 0], kappa=0
table1, thr=[0, 0], kappa=0.5
table1, thr=[0, 0], kappa=1.5
table1, thr=[0, 0], kappa=5
table1, thr=[0, 4], kappa=0
table1, thr=[0, 4], kappa=0.5
table1, thr=[0, 4], kappa=1.5
table1, thr=[0, 4], 

In [14]:
np.set_printoptions(precision=3)
print(table1)
print(table2)
print(table3)

[[ 0.811  0.826  0.831  0.836]
 [ 0.831  0.831  0.816  0.816]
 [ 0.831  0.806  0.836  0.791]
 [ 0.851  0.841  0.846  0.811]]
[[ 0.801  0.861  0.851  0.816]
 [ 0.786  0.816  0.756  0.567]
 [ 0.756  0.781  0.736  0.577]
 [ 0.741  0.766  0.721  0.572]]
[[ 0.836  0.866  0.866  0.776]
 [ 0.811  0.816  0.821  0.791]
 [ 0.826  0.836  0.816  0.697]
 [ 0.801  0.821  0.796  0.697]]


In [28]:
# CREATE TABLE 4 IN LATEX

p_values = np.zeros((4,3))

for idx1, kappa in enumerate([0.5,1.5,5]):
    for idx2, threshold in enumerate([[0,0],[0,4],[4,8],[6,12]]):
        p_values[idx2,idx1] = Metrics.signTest(predictions3['thr={},kappa={}'.format(threshold, kappa)], \
                                               predictions3['thr={},kappa={}'.format(threshold, 0)], \
                                               test.y_data)

In [29]:
print(p_values)

[[ 0.10262  0.10262  0.07864]
 [ 0.11214  0.11104  0.10781]
 [ 0.11104  0.11104  0.02112]
 [ 0.10781  0.11214  0.03766]]


In [17]:
# CREATE TABLE 5 IN LATEX

data = DataHandler(file_dir)
data.readOurData()
data.roundRobinSplit(10)

accuracies = {}

table5 = np.zeros((4,4))

for idx1, threshold in enumerate([[0,0],[0,4],[4,8],[6,12]]):
    for idx2, kappa in enumerate([0,0.5,1.5,5]):
        print('table1, thr={}, kappa={}'.format(threshold, kappa))
        acc = Metrics.roundRobinCV(data,10,NBModel,threshold = threshold, grams = ['uni', 'bi'], smoothing = kappa)
        accuracies['thr={}, kappa={}'.format(threshold, kappa)] = acc
        table5[idx1,idx2] = np.mean(np.array(acc))

  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=[0, 0], kappa=0


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=[0, 0], kappa=0.5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=[0, 0], kappa=1.5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=[0, 0], kappa=5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=[0, 4], kappa=0


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=[0, 4], kappa=0.5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=[0, 4], kappa=1.5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=[0, 4], kappa=5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=[4, 8], kappa=0


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=[4, 8], kappa=0.5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=[4, 8], kappa=1.5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=[4, 8], kappa=5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=[6, 12], kappa=0


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=[6, 12], kappa=0.5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=[6, 12], kappa=1.5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=[6, 12], kappa=5


100%|██████████| 10/10 [01:43<00:00, 10.32s/it]


In [32]:
table5_var = np.zeros((4,4))

for idx1, threshold in enumerate([[0,0],[0,4],[4,8],[6,12]]):
    for idx2, kappa in enumerate([0,0.5,1.5,5]):
        acc = accuracies['thr={}, kappa={}'.format(threshold, kappa)]
        table5_var[idx1,idx2] = np.var(np.array(acc), ddof = 1)


In [25]:
p_values = {}
for idx1, threshold1 in enumerate([[0,0],[0,4],[4,8],[6,12]]):
    for idx2, kappa1 in enumerate([0,0.5,1.5,5]):
        for idx3, threshold2 in enumerate([[0,0],[0,4],[4,8],[6,12]]):
            for idx4, kappa2 in enumerate([0,0.5,1.5,5]):
                p_values['{},{} vs {},{}'.format(threshold1, kappa1, threshold2, kappa2)] = stats.ttest_rel(np.array(accuracies['thr={}, kappa={}'.format(threshold1, kappa1)]),\
                                                                 np.array(accuracies['thr={}, kappa={}'.format(threshold2, kappa2)]))[1]

In [27]:
np.set_printoptions(precision=5)
for key in p_values.keys():
    print(key, ':', p_values[key])


[0, 0],0 vs [0, 0],0 : nan
[0, 0],0 vs [0, 0],0.5 : 0.850442999851
[0, 0],0 vs [0, 0],1.5 : 0.24656307354
[0, 0],0 vs [0, 0],5 : 0.000757375577281
[0, 0],0 vs [0, 4],0 : 0.872288363084
[0, 0],0 vs [0, 4],0.5 : 0.574717331104
[0, 0],0 vs [0, 4],1.5 : 0.343436396138
[0, 0],0 vs [0, 4],5 : 0.467869806395
[0, 0],0 vs [4, 8],0 : 0.904338428508
[0, 0],0 vs [4, 8],0.5 : 0.349637538212
[0, 0],0 vs [4, 8],1.5 : 0.380856181241
[0, 0],0 vs [4, 8],5 : 4.54870480106e-05
[0, 0],0 vs [6, 12],0 : 0.642415137721
[0, 0],0 vs [6, 12],0.5 : 0.715073978679
[0, 0],0 vs [6, 12],1.5 : 0.198857458502
[0, 0],0 vs [6, 12],5 : 1.70813931557e-06
[0, 0],0.5 vs [0, 0],0 : 0.850442999851
[0, 0],0.5 vs [0, 0],0.5 : nan
[0, 0],0.5 vs [0, 0],1.5 : 0.0811261888458
[0, 0],0.5 vs [0, 0],5 : 0.000977343449788
[0, 0],0.5 vs [0, 4],0 : 0.930811405872
[0, 0],0.5 vs [0, 4],0.5 : 0.659621086862
[0, 0],0.5 vs [0, 4],1.5 : 0.77353218863
[0, 0],0.5 vs [0, 4],5 : 0.555445442106
[0, 0],0.5 vs [4, 8],0 : 0.768616004243
[0, 0],0.5 vs [

In [36]:
# CREATING TABLE 6 retraining with blind test set

data = DataHandler(file_dir)
data.readOurData()

train_blind = DataHandler()
test_blind  = DataHandler()

train, test = data.blind_test()
train_blind(train.x_train, train.y_train)
test_blind(test.x_train, test.y_train)

train_blind.roundRobinSplit(10)

100%|██████████| 2009/2009 [00:12<00:00, 159.40it/s]


In [39]:
table1 = np.zeros((4,4))
table2 = np.zeros((4,4))
table3 = np.zeros((4,4))

predictions1 = {}

# table1
for idx1, threshold in enumerate([0,4,8,12]):
    for idx2, kappa in enumerate([0,0.5,1.5,5]):
        print('table1, thr={}, kappa={}'.format(threshold, kappa))
        acc = Metrics.roundRobinCV(train_blind,10,NBModel,threshold = [threshold], grams = 'uni', smoothing = kappa)
        predictions1['M_uni(thr={},kappa={})'.format(threshold, kappa)] = acc
        table1[idx1,idx2] = np.mean(np.array(acc))

# table2
for idx1, threshold in enumerate([0,4,8,12]):
    for idx2, kappa in enumerate([0,0.5,1.5,5]):
        print('table1, thr={}, kappa={}'.format(threshold, kappa))
        acc = Metrics.roundRobinCV(train_blind,10,NBModel,threshold = [threshold], grams = 'bi', smoothing = kappa)
        predictions1['M_bi(thr={},kappa={})'.format(threshold, kappa)] = acc
        table2[idx1,idx2] = np.mean(np.array(acc))
        
# table3
for idx1, threshold in enumerate([[0,0],[0,4],[4,8],[6,12]]):
    for idx2, kappa in enumerate([0,0.5,1.5,5]):
        print('table1, thr={}, kappa={}'.format(threshold, kappa))
        acc = Metrics.roundRobinCV(train_blind,10,NBModel,threshold = threshold, grams = ['uni', 'bi'], smoothing = kappa)
        predictions1['M_joint(thr={},kappa={})'.format(threshold, kappa)] = acc
        table3[idx1,idx2] = np.mean(np.array(acc))

  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=0, kappa=0


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=0, kappa=0.5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=0, kappa=1.5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=0, kappa=5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=4, kappa=0


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=4, kappa=0.5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=4, kappa=1.5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=4, kappa=5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=8, kappa=0


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=8, kappa=0.5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=8, kappa=1.5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=8, kappa=5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=12, kappa=0


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=12, kappa=0.5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=12, kappa=1.5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=12, kappa=5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=0, kappa=0


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=0, kappa=0.5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=0, kappa=1.5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=0, kappa=5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=4, kappa=0


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=4, kappa=0.5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=4, kappa=1.5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=4, kappa=5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=8, kappa=0


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=8, kappa=0.5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=8, kappa=1.5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=8, kappa=5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=12, kappa=0


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=12, kappa=0.5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=12, kappa=1.5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=12, kappa=5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=[0, 0], kappa=0


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=[0, 0], kappa=0.5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=[0, 0], kappa=1.5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=[0, 0], kappa=5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=[0, 4], kappa=0


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=[0, 4], kappa=0.5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=[0, 4], kappa=1.5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=[0, 4], kappa=5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=[4, 8], kappa=0


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=[4, 8], kappa=0.5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=[4, 8], kappa=1.5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=[4, 8], kappa=5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=[6, 12], kappa=0


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=[6, 12], kappa=0.5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=[6, 12], kappa=1.5


  0%|          | 0/10 [00:00<?, ?it/s]

table1, thr=[6, 12], kappa=5


100%|██████████| 10/10 [01:26<00:00,  8.65s/it]


In [43]:
print(table1)
print(table2)
print(table3)

[[ 0.80955  0.80112  0.8073   0.78427]
 [ 0.80112  0.80225  0.79775  0.78483]
 [ 0.80674  0.80393  0.80056  0.77978]
 [ 0.79944  0.79944  0.79382  0.7736 ]]
[[ 0.81404  0.82191  0.82079  0.75843]
 [ 0.80449  0.81461  0.79326  0.73539]
 [ 0.80562  0.81461  0.79607  0.7382 ]
 [ 0.80225  0.80562  0.78933  0.73596]]
[[ 0.81404  0.82191  0.82079  0.75843]
 [ 0.80449  0.81461  0.79326  0.73539]
 [ 0.80562  0.81461  0.79607  0.7382 ]
 [ 0.80225  0.80562  0.78933  0.73596]]


In [4]:
# ------------------ Training
print("training uni")
model_uni      = NBModel(x_train, y_train, threshold = [4], grams = 'uni', smoothing = 0)

print("training bi")
model_bi       = NBModel(x_train, y_train, threshold = [8], grams = 'bi', smoothing = 0)

print("training uni+bi")
model_joint    = NBModel(x_train, y_train, threshold = [4,8], grams = ['uni','bi'], smoothing = 0)

training uni
training bi
training uni+bi


In [5]:
predictions_uni, _   = model_uni.predict(x_test)
predictions_bi, _    = model_bi.predict(x_test)
predictions_joint, _ = model_joint.predict(x_test)

model_uni_sm = model_uni
model_bi_sm = model_bi
model_joint_sm = model_joint

model_uni_sm.smoothing = 0.5
model_bi_sm.smoothing = 0.5
model_joint_sm.smoothing = 0.5

predictions_uni_sm, _   = model_uni.predict(x_test)
predictions_bi_sm, _    = model_bi.predict(x_test)
predictions_joint_sm, _ = model_joint.predict(x_test)


accuracy_uni = Metrics.getAccuracy(predictions_uni, y_test)
accuracy_bi = Metrics.getAccuracy(predictions_bi, y_test)
accuracy_joint = Metrics.getAccuracy(predictions_joint, y_test)

accuracy_uni_sm = Metrics.getAccuracy(predictions_uni_sm, y_test)
accuracy_bi_sm = Metrics.getAccuracy(predictions_bi_sm, y_test)
accuracy_joint_sm = Metrics.getAccuracy(predictions_joint_sm, y_test)

In [6]:
print('Uni gram accuracy no smoothing is {}'.format(accuracy_uni))
print('Bi gram accuracy no smoothing is {}'.format(accuracy_bi))
print('Uni+Bi gram accuracy no smoothing is {}'.format(accuracy_joint))
print('Uni gram accuracy with 0.5 smoothing is {}'.format(accuracy_uni_sm))
print('Bi gram accuracy with 0.5 smoothing is {}'.format(accuracy_bi_sm))
print('Uni+Bi gram accuracy with 0.5 smoothing is {}'.format(accuracy_joint_sm))


Uni gram accuracy no smoothing is {} 0.8208955223880597
Bi gram accuracy no smoothing is {} 0.7164179104477612
Uni+Bi gram accuracy no smoothing is {} 0.8109452736318408
Uni gram accuracy with 0.5 smoothing is {} 0.8208955223880597
Bi gram accuracy with 0.5 smoothing is {} 0.7711442786069652
Uni+Bi gram accuracy with 0.5 smoothing is {} 0.835820895522388


# Sign test

In [7]:
stat_diff = np.zeros((6,6))
predictions = [predictions_uni, predictions_bi, predictions_joint, \
              predictions_uni_sm, predictions_bi_sm, predictions_joint_sm]
for i in range(6):
    for j in range(6):
        stat_diff[i,j] = Metrics.signTest(predictions[i], predictions[j], y_test)

In [8]:
# These models are statistically different
np.transpose(np.array([np.where(stat_diff < 0.05)[0], np.where(stat_diff < 0.05)[1]]))

array([[0, 1],
       [1, 0],
       [1, 2],
       [1, 3],
       [1, 5],
       [2, 1],
       [3, 1],
       [5, 1]])

# Round Robin CV

In [3]:
# This time load all data into an object
data = DataHandler(file_dir)
data.roundRobinSplit(10, )

In [4]:
data.x_data[0]

['Films',
 'adapted',
 'from',
 'comic',
 'books',
 'have',
 'had',
 'plenty',
 'of',
 'success',
 ',',
 'whether',
 'they',
 "'re",
 'about',
 'superheroes',
 '-LRB-',
 'Batman',
 ',',
 'Superman',
 ',',
 'Spawn',
 '-RRB-',
 ',',
 'or',
 'geared',
 'toward',
 'kids',
 '-LRB-',
 'Casper',
 '-RRB-',
 'or',
 'the',
 'arthouse',
 'crowd',
 '-LRB-',
 'Ghost',
 'World',
 '-RRB-',
 ',',
 'but',
 'there',
 "'s",
 'never',
 'really',
 'been',
 'a',
 'comic',
 'book',
 'like',
 'From',
 'Hell',
 'before',
 '.',
 'For',
 'starters',
 ',',
 'it',
 'was',
 'created',
 'by',
 'Alan',
 'Moore',
 '-LRB-',
 'and',
 'Eddie',
 'Campbell',
 '-RRB-',
 ',',
 'who',
 'brought',
 'the',
 'medium',
 'to',
 'a',
 'whole',
 'new',
 'level',
 'in',
 'the',
 'mid',
 "'",
 '80s',
 'with',
 'a',
 '12-part',
 'series',
 'called',
 'The',
 'Watchmen',
 '.',
 'To',
 'say',
 'Moore',
 'and',
 'Campbell',
 'thoroughly',
 'researched',
 'the',
 'subject',
 'of',
 'Jack',
 'the',
 'Ripper',
 'would',
 'be',
 'like',
 'say

In [4]:
accuracies = Metrics.roundRobinCV(data, 10, NBModel, [[4,8], ['uni','bi'], 0.5])

100%|██████████| 10/10 [01:18<00:00,  7.80s/it]


## Parameter tuning (computationally heavy)

In [11]:
results = {}
for thr_1 in [2,4,8,12]:
    for thr_2 in [2,4,8,12]:
        for smth in [0.25, 0.5, 1, 2]:
            accuracies = Metrics.roundRobinCV(data, 10, NBModel, [[thr_1,thr_2], ['uni','bi'], smth])
            results['t1='+str(thr_1)+';t2='+str(thr_2)+';s='+str(smth)] = np.mean(np.array(accuracies))

  0%|          | 0/10 [00:02<?, ?it/s]


KeyboardInterrupt: 

We can use statistical significance testing by averaging out predictions in a CV split and check statistical different per each split?


# Beggining of part 2


In [ ]:
file_dir_our      = "/Users/igoradamski/Documents/cambridge/MLMI/nlp/coursework/nlp/data"
our_data      = DataHandler(file_dir_our)
our_data.readOurData()

train, test   = our_data.blind_test()

cv_train      = DataHandler()
cv_train(train.x_train, train.y_train)